import os
import re

SIMAVR_VERSION = "simavr-1.7"
CORES_DIR = "libraries/simavr/simavr/cores"
CONFIG_FILE = "libraries/simavr/simavr/sim/sim_core_config.h"
DECL_FILE = "libraries/simavr/simavr/sim/sim_core_decl.h"

def generate_headers():
    print(f"Generating sim_core_config.h and sim_core_decl.h...")

    config_content = [
        "// Autogenerated by protosim build script",
        "#ifndef __SIM_CORE_CONFIG_H__",
        "#define __SIM_CORE_CONFIG_H__\n",
        f'#define CONFIG_SIMAVR_VERSION "{SIMAVR_VERSION}"\n'
    ]

    decl_content_top = [
        "// Autogenerated by protosim build script",
        "#ifndef __SIM_CORE_DECL_H__",
        "#define __SIM_CORE_DECL_H__\n",
        '#include "sim_core_config.h"\n'
    ]

    decl_content_bottom = [
        "extern avr_kind_t * avr_kind[];",
        "#ifdef AVR_KIND_DECL",
        "avr_kind_t * avr_kind[] = {"
    ]

    if not os.path.exists(CORES_DIR):
        print(f"Error: {CORES_DIR} not found.")
        return

    for filename in sorted(os.listdir(CORES_DIR)):
        if filename.startswith("sim_") and filename.endswith(".c"):
            core_name = filename[:-2] # remove .c
            upper_name = core_name.upper().replace("SIM_", "")

            # For simplicity in this Windows port, we assume all cores are enabled.
            # The original Makefile probes gcc to see if it compiles, which is slow and mostly true anyway.
            config_content.append(f"#define CONFIG_{upper_name} 1")

            # For decl, we need to extract the avr_kind_t variable name.
            # Usually it matches the filename but sometimes it varies (e.g. sim_mega128 -> m128)
            # The Makefile does: grep -r avr_kind_t cores/ | awk ...
            filepath = os.path.join(CORES_DIR, filename)
            with open(filepath, 'r') as f:
                content = f.read()
                # Looking for: const avr_kind_t m128 = { ... or avr_kind_t m128 = {
                match = re.search(r'avr_kind_t\s+([a-zA-Z0-9_]+)\s*=', content)
                if match:
                    var_name = match.group(1)
                    decl_content_top.append(f"#if CONFIG_{upper_name}")
                    decl_content_top.append(f"extern avr_kind_t {var_name};")
                    decl_content_top.append(f"#endif")

                    decl_content_bottom.append(f"#if CONFIG_{upper_name}")
                    decl_content_bottom.append(f"\t&{var_name},")
                    decl_content_bottom.append(f"#endif")

    config_content.append("\n#endif // __SIM_CORE_CONFIG_H__")

    decl_content_bottom.append("\tNULL")
    decl_content_bottom.append("};")
    decl_content_bottom.append("#endif // AVR_KIND_DECL")
    decl_content_bottom.append("\n#endif // __SIM_CORE_DECL_H__")

    with open(CONFIG_FILE, 'w') as f:
        f.write("\n".join(config_content) + "\n")

    with open(DECL_FILE, 'w') as f:
        f.write("\n".join(decl_content_top) + "\n")
        f.write("\n".join(decl_content_bottom) + "\n")

    print("Headers generated successfully.")

if __name__ == "__main__":
    generate_headers()
